### ISSUE TITLE
How to login "after docker-compose up -d"

### ISSUE THREAD

**Issue by 19317362** [jameskr97/CrashServer#4]
I've read the doc, but have not find the username and passwod to login via http://localhost:8888

**Comment by gaetandezeiraud** [comment]
What is the solution? Same problem here, don't find the username & password.

**Comment by jameskr97** [comment]
There is no default username and password. I've been adding a username and password by a cli in the `crashserver-app` container, and running the command `flask account adduser <email>`. It will autogenerate a password, and you'll be able to use that to login in the web UI.
